First we import the necessary modules

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Next we will load the data

In [2]:
df = pd.read_csv('nhanes2.csv')

In [3]:
df.info(max_cols=None)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Columns: 133 entries, seqn to group
dtypes: bool(21), float64(108), int64(1), object(3)
memory usage: 5.2+ MB

In [4]:
#adding readmission,  new_chf and new_cvd features

df['new_cvd'] = df['cvd_onset_age'] == df['age']
df['readmission'] = df['numhosp'] > 1
df['new_chf'] = df['chf_age'] == df['age']

In [5]:
df.info(max_cols=None)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5992 entries, 0 to 5991
Columns: 136 entries, seqn to new_chf
dtypes: bool(24), float64(108), int64(1), object(3)
memory usage: 5.3+ MB

In [6]:
for column in df.columns:
    print(column)

seqn
age
gender
ethnicity
lang_hisp
lang_nhb_nhw
lang_asian
bmi
depr1
depr2
depr3
depr4
depr5
depr6
depr7
depr8
depr9
depr10
bodyfatpct
foodsec
diabetes
prediabetes
asthma
arthritis
gout
chf
chd
angina
mi
cva
emphysema
thyroid
bronchitis
liver
copd
jaundice
cancer
kidney
asthma_age
arthritis_age
gout_age
diabetes_age
chf_age
chd_age
angina_age
mi_age
cva_age
emphysema_age
thyroid_age
bronchitis_age
liver_age
jaundice_age
ca_bladder_age
ca_testicular_age
ca_blood_age
ca_thyroid_age
ca_bone_age
ca_uterine_age
ca_brain_age
ca_breast_age
ca_cervical_age
ca_colon_age
ca_esophageal_age
ca_gallbladder_age
ca_kidney_age
ca_larynx_age
ca_leukemia_age
ca_liver_age
ca_lung_age
ca_hodgkins_age
ca_melanoma_age
ca_mouth_age
ca_nervous_age
ca_ovarian_age
ca_pancreatic_age
ca_prostate_age
ca_rectal_age
ca_skin_nonmelanoma_age
ca_skin_unknown_age
ca_softtissue_age
ca_stomach_age
numhosp
fglucose
hdl
tg
ldl
tchol
hgba1c
wbc
lymphocytes
monocytes
neutrophils
eosinophil
basophils
rbc
hgb
hct
mcv
mch
mchgb
rdw
plt
mpv
alb
alp
ast
alt
bun
bicarbonate
calcium
cholesterol
cpk
chlorine
creatinine
globulin
glucose
ggt
iron
potassium
ldh
sodium
osmolality
phosphorus
tbili
protein
triglycerides
uricacid
depr_score
cvd_onset_age
group_1
group_2
group_0
group
new_cvd
readmission
new_chf

In [12]:
pd.set_option('display.max_columns', None)

df.describe()

,seqn,age,gender,lang_nhb_nhw,bmi,depr1,depr2,depr3,depr4,depr5,depr6,depr7,depr8,depr9,depr10,bodyfatpct,foodsec,asthma_age,arthritis_age,gout_age,diabetes_age,chf_age,chd_age,angina_age,mi_age,cva_age,emphysema_age,thyroid_age,bronchitis_age,liver_age,jaundice_age,ca_bladder_age,ca_testicular_age,ca_blood_age,ca_thyroid_age,ca_bone_age,ca_uterine_age,ca_brain_age,ca_breast_age,ca_cervical_age,ca_colon_age,ca_esophageal_age,ca_gallbladder_age,ca_kidney_age,ca_larynx_age,ca_leukemia_age,ca_liver_age,ca_lung_age,ca_hodgkins_age,ca_melanoma_age,ca_mouth_age,ca_nervous_age,ca_ovarian_age,ca_pancreatic_age,ca_prostate_age,ca_rectal_age,ca_skin_nonmelanoma_age,ca_skin_unknown_age,ca_softtissue_age,ca_stomach_age,numhosp,fglucose,hdl,tg,ldl,tchol,hgba1c,wbc,lymphocytes,monocytes,neutrophils,eosinophil,basophils,rbc,hgb,hct,mcv,mch,mchgb,rdw,plt,mpv,alb,alp,ast,alt,bun,bicarbonate,calcium,cholesterol,cpk,chlorine,creatinine,globulin,glucose,ggt,iron,potassium,ldh,sodium,osmolality,phosphorus,tbili,protein,triglycerides,uricacid,depr_score,cvd_onset_age,group
count,5992.000000,5992.000000,5992.0,3294.000000,5662.000000,5164.000000,5164.000000,5164.000000,5162.000000,5162.000000,5162.000000,5161.000000,5161.000000,5161.000000,3579.000000,3012.000000,5766.000000,887.000000,1433.000000,263.000000,830.000000,209.000000,239.000000,131.000000,246.000000,205.000000,121.000000,610.000000,296.000000,256.000000,163.000000,22.000000,4.000000,1.0,13.000000,2.00000,32.000000,0.0,84.000000,22.000000,36.000000,2.000000,0.0,8.000000,0.0,13.000000,6.000000,15.00000,11.000000,44.000000,4.000000,0.0,21.000000,3.000000,97.000000,2.000000,44.000000,53.000000,0.0,4.000000,5992.000000,2573.000000,5394.000000,2363.000000,2339.000000,5394.000000,5441.000000,5423.000000,5422.000000,5422.000000,5422.000000,5.422000e+03,5422.000000,5423.000000,5423.000000,5423.000000,5423.000000,5423.000000,5439.000000,5423.000000,5423.000000,5423.000000,5386.000000,5385.000000,5386.000000,5386.000000,5385.000000,5387.000000,5387.000000,5384.000000,5378.000000,5387.000000,5385.000000,5382.000000,5387.000000,5386.000000,5383.000000,5387.000000,5386.000000,5387.000000,5384.000000,5386.000000,5.384000e+03,5383.000000,5384.000000,5384.000000,3579.000000,625.000000,5992.000000
mean,88676.950935,48.121996,0.0,1.029751,29.382197,0.422541,0.346631,0.617157,0.783611,0.407400,0.248741,0.258865,0.168378,0.062779,0.290305,32.855644,2.628859,21.099211,49.081647,50.174905,48.933735,57.143541,57.029289,49.358779,56.662602,55.751220,52.776860,44.714754,35.324324,42.484375,24.895706,66.772727,42.000000,70.0,49.230769,70.50000,42.875000,NaN,55.464286,31.136364,58.500000,67.500000,NaN,57.750000,NaN,45.076923,54.000000,68.60000,48.000000,57.909091,61.500000,NaN,42.047619,47.666667,64.309278,53.500000,57.909091,60.358491,NaN,56.750000,0.170561,112.764866,54.134779,112.610664,111.394186,189.096218,5.822000,7.364503,31.027591,8.137403,57.297990,2.847510e+00,0.814367,4.742095,13.912299,41.836898,88.496515,29.413885,33.214948,13.823898,239.179974,8.367158,4.314779,70.002786,25.795767,25.224285,14.609656,24.463152,9.348023,192.009287,157.993492,103.228513,0.876449,2.872947,104.603304,28.346082,80.943526,3.940590,129.157631,138.642658,277.412519,3.697883,5.501207e-01,7.187628,155.264302,5.395877,5.054484,54.716800,0.145861
std,2877.819691,18.521353,0.0,1.707514,7.095921,0.872461,0.719062,0.946989,0.931202,0.817394,0.661830,0.686266,0.578470,0.397585,0.616834,8.769377,0.628847,19.795833,16.074796,15.236301,14.504912,14.227495,12.925903,13.016007,12.620197,17.013304,14.200051,17.988428,20.774892,16.785140,14.918964,17.380700,10.099505,NaN,19.744847,2.12132,15.638559,NaN,13.004583,9.453120,13.299839,4.949747,NaN,17.547894,NaN,23.834364,13.841965,10.87461,22.627417,16.607393,15.264338,NaN,17.133231,7.094599,7.902216,0.707107,16.607393,13.756249,NaN,17.385339,0.584917,40.589287,17.482290,94.975410,35.831075,41.717568,1.165878,2.718909,8.689835,2.167803,9.460388,2.113315e+00,0.331501,0.506885,1.561588,4.283877,6.117493,2.463883,0.962150,1.360295,61.811458,0.926347,0.353884,23.630761,16.767310,17.608499,5.908784,2.220129,0.349528,42.942469,184.032256,2.905547,0.420188,0.443718,42.709376,44.854219,34.472817,0.337492,28.615211,2.160696,4.918900,0.552152,2.876300e-01,0.463418,130.495932,1.429425,4.942271,15.144543,0.438986
min,83732.000000,18.000000,0.0,1.000000,14.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.700000,1.000000,1.000000,2.000000,18.000000,3.000000,0.000000,10.000000,10.000000,20.000000,2.000000,13.000000,8.000000,0.000000,5.000000,2.000000,7.000000,30.000000,70.0,28.000000,69.00000,18.000000,NaN,25.000000,16.000000,15.000000,64.000000,NaN,27.000000,NaN,3.000000,30.000000,40.00000,19.000000,15.000000,44.000000,NaN,18.000000,40.000000,46.000000,53.000000,15.000000,30.000000,NaN,42.000000,0.000000,21.000000,6.000000,15.000000,23.000000,77.000000,3.800000,1.400000,3.700000,1.400000,3.600000,5.397605e-79,0.100000,2.520000,6.200000,21.800000,50.800000,14.600000,27.100000,11.500000,14.000000,5.600000,2.000000,23.000000,8.000000,6.000000,3.000000,15.000000,7.700000,78.000000,17.000000,88.000000,0.320000,1.600000,19.000000,4.000000,2.000000,2.600000,51.000000,124.000000,250.000000,1.000000,5.397605e-79,5.200000,13.000000,1.600000,1.000000,0.000000,0.000000
25%,86175.750000,32.000000,0.0,1.000000,24.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,26.300000,2.000000,6.000000,39.000000,40.000000,40.000000,48.000000,49.000000,41.000000,48.000000,47.000000,44.000000,30.000000,17.000000,30.000000,13.000000,57.000000,36.750000,70.0,35.000000,69.75000,27.500000,NaN,46.000000,26.000000,51.750000,65.750000,NaN,49.000000,NaN,26.000000,50.500000,63.50000,29.000000,46.000000,53.000000,NaN,26.000000,44.500000,59.000000,53.250000,46.000000,52.000000,NaN,44.250000,0.000000,95.000000,42.000000,62.000000,85.500000,160.000000,5.300000,5.800000,25.300000,6.600000,51.400000,1.500000e+00,0.600000,4.410000,12.900000,39.100000,85.800000,28.400000,32.700000,13.000000,198.000000,7.700000,4.100000,55.000000,20.000000,16.000000,11.000000,23.000000,9.100000,162.000000,75.000000,101.000000,0.680000,2.600000,86.000000,14.000000,57.000000,3.720000,111.000000,137.000000,274.000000,3.300000,4.000000e-01,6.900000,79.000000,4.400000,2.000000,46.000000,0.000000
50%,88659.500000,48.000000,0.0,1.000000,28.300000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32.850000,3.000000,12.000000,50.000000,50.000000,50.000000,58.000000,57.000000,50.000000,57.000000,58.000000,54.000000,45.000000,34.500000,43.000000,21.000000,71.500000,42.000000,70.0,40.000000,70.50000,43.500000,NaN,55.000000,30.000000,63.000000,67.500000,NaN,61.000000,NaN,46.000000,55.000000,71.00000,49.000000,60.000000,61.000000,NaN,37.000000,49.000000,65.000000,53.500000,60.000000,58.000000,NaN,52.500000,0.000000,102.000000,51.000000,91.000000,109.000000,186.000000,5.500000,7.000000,30.500000,7.900000,57.800000,2.300000e+00,0.800000,4.730000,14.000000,41.900000,89.100000,29.800000,33.300000,13.500000,234.000000,8.300000,4.300000,66.000000,23.000000,21.000000,14.000000,25.000000,9.300000,189.000000,112.000000,103.000000,0.830000,2.800000,93.000000,19.000000,77.000000,3.920000,125.000000,139.000000,277.000000,3.700000,5.000000e-01,7.200000,120.500000,5.300000,3.000000,55.000000,0.000000
75%,91174.250000,63.000000,0.0,1.000000,33.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,39.900000,3.000000,34.500000,60.000000,60.000000,60.000000,68.000000,66.000000,58.000000,66.000000,68.000000,61.000000,58.000000,51.000000,56.000000,33.500000,80.000000,47.250000,70.0,69.000000,71.25000,57.000000,NaN,63.500000,36.750000,65.000000,69.250000,NaN,72.250000,NaN,63.000000,63.250000,76.50000,63.000000,70.000000,69.500000,NaN,59.000000,51.500000,69.000000,53.750000,70.000000,71.000000,NaN,65.000000,0.000000,113.000000,64.000000,137.000000,133.000000,213.000000,5.900000,8.500000,36.400000,9.375000,63.500000,3.600000e+00,1.000000,5.070000,15.000000,44.800000,92.300000,31.000000,33.800000,14.200000,273.000000,8.900000,4.500000,81.000000,28.000000,28.000000,17.000000,26.000000,9.600000,217.000000,178.000000,105.000000,0.990000,3.100000,105.000000,29.000000,100.000000,4.140000,143.000000,140.000000,280.000000,4.100000,7.000000e-01,7.500000,190.000000,6.300000,7.000000,65.000000,0.000000
max,93702.000000,80.000000,0.0,99.000000,67.300000,9.000000,7.000000,9.000000,7.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,54.700000,3.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,79.000000,80.000000,80.000000,80.000000,68.000000,80.000000,54.000000,70.0,80.000000,72.00000,66.000000,NaN,80.000000,54.000000,80.000000,71.000000,NaN,76.000000,NaN,80.000000,69.000000,80.00000,80.000000,80.000000,80.000000,NaN,74.000000,54.000000,80.000000,54.000000,80.000000,80.000000,NaN,80.000000,6.000000,479.000000,226.000000,2141.000000,277.000000,545.000000,17.000000,117.200000,94.500000,29.300000,93.200000,2.130000e+01,4.000000,7.900000,19.200000,59.100000,115.600000,38.500000,36.400000,26.400000,777.000000,15.100000,5.400000,384.000000,832.000000,319.000000,96.000000,34.000000,11.500000,565.000000,3963.000000,117.000000,10.710000,7.000000,610.000000,1487.000000,286.000000,5.860000,618.000000,161.000000,322.000000,8.200000,3.300000e+00,10.100000,3061.000000,18.000000,49.000000,80.000000,2.000000

In [14]:
pd.set_option('display.max_rows', None)

df.count()

seqn                       5992
age                        5992
gender                     5992
ethnicity                  5992
lang_hisp                  1851
lang_nhb_nhw               3294
lang_asian                  723
bmi                        5662
depr1                      5164
depr2                      5164
depr3                      5164
depr4                      5162
depr5                      5162
depr6                      5162
depr7                      5161
depr8                      5161
depr9                      5161
depr10                     3579
bodyfatpct                 3012
foodsec                    5766
diabetes                   5992
prediabetes                5992
asthma                     5992
arthritis                  5992
gout                       5992
chf                        5992
chd                        5992
angina                     5992
mi                         5992
cva                        5992
emphysema                  5992
thyroid                    5992
bronchitis                 5992
liver                      5992
copd                       5992
jaundice                   5992
cancer                     5992
kidney                     5992
asthma_age                  887
arthritis_age              1433
gout_age                    263
diabetes_age                830
chf_age                     209
chd_age                     239
angina_age                  131
mi_age                      246
cva_age                     205
emphysema_age               121
thyroid_age                 610
bronchitis_age              296
liver_age                   256
jaundice_age                163
ca_bladder_age               22
ca_testicular_age             4
ca_blood_age                  1
ca_thyroid_age               13
ca_bone_age                   2
ca_uterine_age               32
ca_brain_age                  0
ca_breast_age                84
ca_cervical_age              22
ca_colon_age                 36
ca_esophageal_age             2
ca_gallbladder_age            0
ca_kidney_age                 8
ca_larynx_age                 0
ca_leukemia_age              13
ca_liver_age                  6
ca_lung_age                  15
ca_hodgkins_age              11
ca_melanoma_age              44
ca_mouth_age                  4
ca_nervous_age                0
ca_ovarian_age               21
ca_pancreatic_age             3
ca_prostate_age              97
ca_rectal_age                 2
ca_skin_nonmelanoma_age      44
ca_skin_unknown_age          53
ca_softtissue_age             0
ca_stomach_age                4
numhosp                    5992
fglucose                   2573
hdl                        5394
tg                         2363
ldl                        2339
tchol                      5394
hgba1c                     5441
wbc                        5423
lymphocytes                5422
monocytes                  5422
neutrophils                5422
eosinophil                 5422
basophils                  5422
rbc                        5423
hgb                        5423
hct                        5423
mcv                        5423
mch                        5423
mchgb                      5439
rdw                        5423
plt                        5423
mpv                        5423
alb                        5386
alp                        5385
ast                        5386
alt                        5386
bun                        5385
bicarbonate                5387
calcium                    5387
cholesterol                5384
cpk                        5378
chlorine                   5387
creatinine                 5385
globulin                   5382
glucose                    5387
ggt                        5386
iron                       5383
potassium                  5387
ldh                        5386
sodium                     5387
osmolality                 5384
phosphorus                 5386
tbili                      5384
protein                    5383
triglycerides              5384
uricacid                   5384
depr_score                 3579
cvd_onset_age               625
group_1                    5992
group_2                    5992
group_0                    5992
group                      5992
new_cvd                    5992
readmission                5992
new_chf                    5992
dtype: int64

In [15]:
df.numhosp.value_counts()

0.0    5322
1.0     466
2.0     120
3.0      49
4.0      14
5.0      13
6.0       8
Name: numhosp, dtype: int64

In [16]:
df.readmission.value_counts()

False    5788
True      204
Name: readmission, dtype: int64

In [17]:
df.head()

,seqn,age,gender,ethnicity,lang_hisp,lang_nhb_nhw,lang_asian,bmi,depr1,depr2,depr3,depr4,depr5,depr6,depr7,depr8,depr9,depr10,bodyfatpct,foodsec,diabetes,prediabetes,asthma,arthritis,gout,chf,chd,angina,mi,cva,emphysema,thyroid,bronchitis,liver,copd,jaundice,cancer,kidney,asthma_age,arthritis_age,gout_age,diabetes_age,chf_age,chd_age,angina_age,mi_age,cva_age,emphysema_age,thyroid_age,bronchitis_age,liver_age,jaundice_age,ca_bladder_age,ca_testicular_age,ca_blood_age,ca_thyroid_age,ca_bone_age,ca_uterine_age,ca_brain_age,ca_breast_age,ca_cervical_age,ca_colon_age,ca_esophageal_age,ca_gallbladder_age,ca_kidney_age,ca_larynx_age,ca_leukemia_age,ca_liver_age,ca_lung_age,ca_hodgkins_age,ca_melanoma_age,ca_mouth_age,ca_nervous_age,ca_ovarian_age,ca_pancreatic_age,ca_prostate_age,ca_rectal_age,ca_skin_nonmelanoma_age,ca_skin_unknown_age,ca_softtissue_age,ca_stomach_age,numhosp,fglucose,hdl,tg,ldl,tchol,hgba1c,wbc,lymphocytes,monocytes,neutrophils,eosinophil,basophils,rbc,hgb,hct,mcv,mch,mchgb,rdw,plt,mpv,alb,alp,ast,alt,bun,bicarbonate,calcium,cholesterol,cpk,chlorine,creatinine,globulin,glucose,ggt,iron,potassium,ldh,sodium,osmolality,phosphorus,tbili,protein,triglycerides,uricacid,depr_score,cvd_onset_age,group_1,group_2,group_0,group,new_cvd,readmission,new_chf
0,83732.0,62.0,0.0,white,NaN,1.0,NaN,27.8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,3.0,True,True,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,False,NaN,40.0,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,0.0,NaN,46.0,NaN,NaN,173.0,7.0,9.8,23.9,8.2,63.5,4.0,0.5,4.93,15.2,44.7,90.8,30.8,34.0,13.9,181.0,8.3,4.6,52.0,21.0,25.0,13.0,25.0,9.8,172.0,203.0,100.0,0.90,2.9,94.0,22.0,70.0,4.30,110.0,136.0,272.0,4.7,0.5,7.5,158.0,4.2,1.0,NaN,False,False,True,0,False,False,False
1,83733.0,53.0,0.0,white,NaN,NaN,NaN,30.8,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,30.0,3.0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,101.0,63.0,147.0,173.0,265.0,5.5,7.3,31.3,9.7,54.8,2.6,1.8,4.89,17.5,49.7,101.8,35.8,35.1,13.4,170.0,9.6,4.5,47.0,31.0,35.0,10.0,27.0,9.8,267.0,91.0,103.0,1.05,2.9,94.0,75.0,161.0,4.55,108.0,140.0,278.0,4.4,0.6,7.4,170.0,7.0,2.0,NaN,False,False,True,0,False,False,False
2,83734.0,78.0,0.0,white,NaN,1.0,NaN,28.8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,3.0,True,True,True,True,False,False,False,True,True,False,True,True,False,True,True,True,True,True,60.0,55.0,NaN,52.0,NaN,NaN,NaN,58.0,NaN,59.0,39.0,NaN,11.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,NaN,NaN,0.0,84.0,30.0,269.0,145.0,229.0,5.8,4.4,29.9,9.6,55.8,3.9,0.9,4.18,12.4,37.9,90.8,29.6,32.6,14.7,223.0,9.0,4.5,46.0,30.0,29.0,26.0,24.0,9.7,236.0,160.0,106.0,1.12,2.8,103.0,11.0,72.0,4.70,151.0,140.0,284.0,3.6,0.5,7.3,299.0,7.3,2.0,58.0,False,False,True,0,False,False,False
3,83735.0,56.0,0.0,white,NaN,1.0,NaN,42.4,1.0,1.0,2.0,2.0,1.0,3.0,2.0,0.0,1.0,0.0,50.9,3.0,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,61.0,NaN,NaN,174.0,5.6,6.1,17.1,10.3,68.7,3.1,0.9,4.54,12.8,40.1,88.3,28.2,31.9,13.1,280.0,9.1,3.8,65.0,23.0,26.0,13.0,24.0,8.9,179.0,66.0,106.0,0.96,2.3,63.0,19.0,43.0,4.08,172.0,141.0,279.0,3.8,0.3,6.1,93.0,5.4,13.0,NaN,False,False,True,0,False,False,False
4,83736.0,42.0,0.0,black,NaN,1.0,NaN,20.3,1.0,1.0,1.0,1.0,3.0,0.0,1.0,0.0,0.0,0.0,NaN,2.0,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,84.0,53.0,47.0,142.0,204.0,5.6,4.2,47.1,7.8,44.8,0.2,0.2,4.16,12.1,36.5,87.8,29.1,33.2,12.3,275.0,7.7,4.3,46.0,20.0,13.0,12.0,24.0,9.3,202.0,67.0,99.0,0.64,3.4,83.0,23.0,44.0,3.50,93.0,136.0,270.0,3.2,0.3,7.7,52.0,3.3,8.0,NaN,False,False,True,0,False,False,False